### ISSUE TITLE
Formatter crashes on comments

### ISSUE THREAD

**Issue by sirikid** [sonercirit/prettieex#1]
**How to reproduce:** try to format any file with HTML comments
**Example error:**
```
14:07:42.652 [error] Task #PID<0.95.0> started from #PID<0.393.0> terminating
** (FunctionClauseError) no function clause matching in String.Break.trim_leading/1
    (elixir 1.10.3) lib/elixir/unicode/properties.ex:298: String.Break.trim_leading({:comment, " Facebook Pixel Code "})
    (elixir 1.10.3) lib/string.ex:1177: String.trim/1
    lib/eex_formatter.ex:111: EExFormatter.prettify_tag/3
    (elixir 1.10.3) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/eex_formatter.ex:98: EExFormatter.prettify_tag/3
    (elixir 1.10.3) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/eex_formatter.ex:98: EExFormatter.prettify_tag/3
    (elixir 1.10.3) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
Function: #Function<2.89779105/0 in Mix.Tasks.Prettieex.run/1>
    Args: []
```

**Comment by sonercirit** [comment]
This has been resolved with #2 .
